version: '3.8'
services:
  db:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
      MONGO_INITDB_DATABASE: MongoDB
    volumes:
      - db-data:/data/db
    networks:
      - app-network
    ports:
      - "27017:27017"

  api:
    build: ./api
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - app-net

  web:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - app-net

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - MONGO_HOST: db
      - MONGO_PORT: 27017
    networks:
      app-net
networks:
  app-net: